Easy Tasks
1 SELECT 
  CAST(EMPLOYEE_ID AS VARCHAR) + '-' + FIRST_NAME + ' ' + LAST_NAME AS FullName
FROM 
  Employees
WHERE 
  EMPLOYEE_ID = 100;

2 UPDATE Employees
SET PHONE_NUMBER = REPLACE(PHONE_NUMBER, '124', '999')
WHERE PHONE_NUMBER LIKE '%124%';

3  SELECT 
  FIRST_NAME AS "First Name",
  LENGTH(FIRST_NAME) AS "Name Length"
FROM Employees
WHERE FIRST_NAME LIKE 'A%' 
   OR FIRST_NAME LIKE 'J%' 
   OR FIRST_NAME LIKE 'M%'
ORDER BY FIRST_NAME;

4  SELECT 
  MANAGER_ID,
  SUM(SALARY) AS Total_Salary
FROM Employees
GROUP BY MANAGER_ID;

5 
